### ISSUE TITLE
unter ubuntu fehlen noch libs für die installation von lxml

### ISSUE THREAD

**Issue by kinkerl** [randomknowledge/mwt#1]
lösung:
sudo apt-get install libxml2-dev libxslt-dev  

sollte vllt in die doku

**Comment by randomknowledge** [comment]
Bist jetzt collaborator, damit solltest du's auch selbst ändern können.

**Comment by kinkerl** [comment]
ich mach das dann einfach in meinem fork und pull dann rüber. is schöner :)
